//---------- ----------------------------- ----------
//---------- !!! AUTOGENERATED CONTENT !!! ----------
//---------- ----------------------------- ----------

//Runtime Monitoring
//File generated: 2022-06-07 21:51:16Z
//Please dont change the contents of this file. Otherwise IL2CPP runtime may not work with runtime monitoring!
//Ensure that this file is located in Assembly-CSharp. Otherwise this file may not compile.
//https://github.com/JohnBaracuda/Runtime-Monitoring

#if ENABLE_IL2CPP && !DISABLE_MONITORING

internal class IL2CPP_AOT
{
    //FieldProfile<World, long>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<World, System.Int64> AOT_GENERATED_TYPE_0;
    
    //FieldUnit<World, long>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<World, System.Int64> AOT_GENERATED_TYPE_2;
    
    //FieldProfile<PlayerMovement, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Boolean> AOT_GENERATED_TYPE_4;
    
    //FieldUnit<PlayerMovement, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Boolean> AOT_GENERATED_TYPE_6;
    
    //FieldProfile<PlayerMovement, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Boolean> AOT_GENERATED_TYPE_8;
    
    //FieldUnit<PlayerMovement, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Boolean> AOT_GENERATED_TYPE_10;
    
    //FieldProfile<PlayerMovement, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Int32> AOT_GENERATED_TYPE_12;
    
    //FieldUnit<PlayerMovement, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Int32> AOT_GENERATED_TYPE_14;
    
    //FieldProfile<PlayerMovement, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Single> AOT_GENERATED_TYPE_16;
    
    //FieldUnit<PlayerMovement, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Single> AOT_GENERATED_TYPE_18;
    
    //FieldProfile<PlayerMovement, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Boolean> AOT_GENERATED_TYPE_20;
    
    //FieldUnit<PlayerMovement, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.PlayerMovement, System.Boolean> AOT_GENERATED_TYPE_22;
    
    //FieldProfile<PlayerWeapon, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.PlayerWeapon, System.Int32> AOT_GENERATED_TYPE_24;
    
    //FieldUnit<PlayerWeapon, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.PlayerWeapon, System.Int32> AOT_GENERATED_TYPE_26;
    
    //FieldProfile<ShootingTarget, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.ShootingTarget, System.Boolean> AOT_GENERATED_TYPE_28;
    
    //FieldUnit<ShootingTarget, bool>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.ShootingTarget, System.Boolean> AOT_GENERATED_TYPE_30;
    
    //FieldProfile<ShootingTarget, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.ShootingTarget, System.Single> AOT_GENERATED_TYPE_32;
    
    //FieldUnit<ShootingTarget, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.ShootingTarget, System.Single> AOT_GENERATED_TYPE_34;
    
    //PropertyProfile<FPSMonitor, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.PropertyProfile<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Int32> AOT_GENERATED_TYPE_36;
    
    //PropertyUnit<FPSMonitor, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.PropertyUnit<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Int32> AOT_GENERATED_TYPE_38;
    
    //PropertyProfile<FPSMonitor, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.PropertyProfile<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Int32> AOT_GENERATED_TYPE_40;
    
    //PropertyUnit<FPSMonitor, int>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.PropertyUnit<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Int32> AOT_GENERATED_TYPE_42;
    
    //FieldProfile<FPSMonitor, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Profiling.FieldProfile<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Single> AOT_GENERATED_TYPE_44;
    
    //FieldUnit<FPSMonitor, float>
    [UnityEngine.Scripting.PreserveAttribute]
    Baracuda.Monitoring.Internal.Units.FieldUnit<Baracuda.Monitoring.Example.Scripts.Persistent.FPSMonitor, System.Single> AOT_GENERATED_TYPE_46;
    
}
#endif //ENABLE_IL2CPP && !DISABLE_MONITORING
